--- 
title: "Molecular mechanisms underlying response to influenza in grey seals (*Halichoerus grypus*), a potential wild reservoir"
author: "Christina M. McCosker"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
suppresss-bibliography: true
---

# Publication Information
McCosker, C. M., Unal, E., Gigliotti, A., Puryear, W. B., Runstadler, J. A., Murray, K. T., King, B. L., & Cammen, K. M. (2025). Molecular Mechanisms Underlying Response to Influenza in Grey Seals (*Halichoerus grypus*), a Potential Wild Reservoir. Molecular Ecology, e70012. https://doi.org/10.1111/mec.70012

## Authors 
Christina M. McCosker^1^, Ebru Unal^2,3^, Alayna Gigliotti^1^, Wendy B. Puryear^4^, Jonathan A. Runstadler^4^, Kimberly T. Murray^5^, Benjamin L. King^6^, Kristina M. Cammen^1^  

*^1^School of Marine Sciences, University of Maine, Orono, ME, USA*  
*^2^Mystic Aquarium, Mystic, CT, USA*  
*^3^Department of Marine Sciences, University of Connecticut, Groton, CT, USA*  
*^4^ Cummings School of Veterinary Medicine, Tufts University, North Grafton, MA, USA*   
*^5^ NOAA Northeast Fisheries Science Center, Woods Hole, MA, USA*  
*^6^ Department of Molecular and Biomedical Sciences, University of Maine, Orono, ME, USA*  

## Abstract
RNA viruses are infamous for their ability to cross species barriers, posing threats to global health and security. Influenza A virus (IAV) is naturally found in avian hosts but periodically spills over into marine wildlife. IAV outbreaks occur in the Northwest Atlantic, but grey seals (*Halichoerus grypus*) appear to be less susceptible to IAV compared to other species. The subclinical nature of IAV infection in addition to life history factors suggest grey seals are a potential wild reservoir host for IAV. We investigated differential gene expression among grey seals naturally exposed to IAV to elucidate genetic mechanisms involved in grey seal disease resistance. RNA sequencing was conducted on blood samples (N = 31) collected from grey seal pups in Massachusetts, US between 2014 and 2019. Samples were grouped for analysis based on presence/absence of viral RNA and antibodies. In the presence of IAV RNA, we observed widespread down-regulation of genes, including immune genes, potentially as a result of IAV-induced host shutoff. Immune down-regulation occurred in acute stage of IAV infection (+ viral RNA, - antibodies), followed by up-regulation of protein production in peak stage (+ viral RNA, + antibodies), possibly as a result of increased viral replication. Evidence of an activated immune response was observed in late stage of infection (- viral RNA, + antibodies) with up-regulated adaptive immunity genes. We hypothesize that the combination of down- and up-regulated immune gene expression may prevent overstimulation of the immune response, acting as an adaptation in grey seals to resist IAV-associated mortality.

